site_name: Future Lab Docs
theme:
  name: 'material'
markdown_extensions:
  - codehilite
nav:
  - Inicio: index.md
  - About: about.md
  - Reglamento: reglas.md
  - Organigrama: organigrama.md
  - Resumen-Ejecutivo: resumen.md
  - Metrics: metrics.md
